import hashlib
import json
import re
import sqlite3
from contextlib import contextmanager
from datetime import UTC, datetime
from threading import Lock
from typing import Any
from uuid import uuid4

import psycopg
from psycopg_pool import ConnectionPool

from .config import settings

INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)
_pool: ConnectionPool | None = None
_pool_lock = Lock()
# Critical read/modify/write operations share one transaction-scoped lock, matching
# SQLite's single-writer behavior. This app still runs as one process/instance.
_write_lock_id = 731946201
_sql_tokens = re.compile(r"'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|\?")


class Record(dict):
    """Keep SQLite's name/index lookup contract on PostgreSQL result rows."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


def _record_factory(cursor):
    columns = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Record(zip(columns, values))


class PostgresConnection:
    def __init__(self, connection):
        self.connection = connection

    def execute(self, query: str, parameters=None):
        # Translate placeholders in our static SQL only, never parameter values.
        # Quoted SQL literals/identifiers remain literal; values stay driver-bound.
        if parameters is not None:
            query = _sql_tokens.sub(
                lambda match: "%s" if match[0] == "?" else match[0], query.replace("%", "%%")
            )
        return self.connection.execute(query, parameters)


def _postgres_pool():
    global _pool
    with _pool_lock:
        if _pool is None:
            _pool = ConnectionPool(
                settings().database_url.get_secret_value(),
                min_size=0,
                max_size=5,
                max_waiting=40,
                timeout=20,
                max_idle=60,
                reconnect_timeout=20,
                check=ConnectionPool.check_connection,
                kwargs={"row_factory": _record_factory, "connect_timeout": 15, "prepare_threshold": None},
                open=True,
            )
        return _pool


def close_pool():
    global _pool
    with _pool_lock:
        if _pool is not None:
            _pool.close()
            _pool = None


def begin_write(connection):
    if isinstance(connection, PostgresConnection):
        connection.execute("SELECT pg_advisory_xact_lock(?)", (_write_lock_id,))
    else:
        connection.execute("BEGIN IMMEDIATE")


def now() -> str:
    return datetime.now(UTC).isoformat()


def uid() -> str:
    return uuid4().hex


def encode(value: Any) -> str:
    return json.dumps(value, separators=(",", ":"), sort_keys=True, ensure_ascii=False)


def digest(value: Any) -> str:
    return hashlib.sha256(encode(value).encode()).hexdigest()


@contextmanager
def connect():
    if settings().database_url.get_secret_value():
        with _postgres_pool().connection() as connection:
            connection.execute("SET LOCAL statement_timeout = '30s'")
            connection.execute("SET LOCAL lock_timeout = '15s'")
            yield PostgresConnection(connection)
        return
    settings().data_dir.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(settings().data_dir / "marginguard.sqlite3", timeout=15)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=15000")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def initialize():
    with connect() as c:
        postgres = isinstance(c, PostgresConnection)
        if postgres:
            begin_write(c)
        else:
            c.execute("PRAGMA journal_mode=WAL")
        audit_id = "BIGINT GENERATED BY DEFAULT AS IDENTITY" if postgres else "INTEGER"
        audit_key = "PRIMARY KEY" if postgres else "PRIMARY KEY AUTOINCREMENT"
        schema = """
        CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY);
        INSERT INTO schema_version VALUES(1) ON CONFLICT DO NOTHING;
        CREATE TABLE IF NOT EXISTS users(
            id TEXT PRIMARY KEY, email TEXT UNIQUE, name TEXT NOT NULL,
            password_hash TEXT, is_demo INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS workspaces(
            id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL, active_dataset_id TEXT,
            scenario_json TEXT NOT NULL DEFAULT '{}', scenario_hash TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        );
        CREATE UNIQUE INDEX IF NOT EXISTS workspace_owner ON workspaces(owner_id);
        CREATE TABLE IF NOT EXISTS sessions(
            token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            csrf TEXT NOT NULL, expires_at DOUBLE PRECISION NOT NULL
        );
        CREATE TABLE IF NOT EXISTS datasets(
            id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            version INTEGER NOT NULL, name TEXT NOT NULL, content_hash TEXT NOT NULL,
            snapshot TEXT NOT NULL, summary TEXT NOT NULL, issues TEXT NOT NULL,
            status TEXT NOT NULL, synthetic INTEGER NOT NULL, created_at TEXT NOT NULL,
            UNIQUE(workspace_id,version)
        );
        CREATE TABLE IF NOT EXISTS runs(
            id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            dataset_id TEXT NOT NULL REFERENCES datasets(id), question TEXT NOT NULL,
            status TEXT NOT NULL, mode TEXT NOT NULL, stage TEXT NOT NULL,
            events TEXT NOT NULL DEFAULT '[]', result TEXT, state TEXT NOT NULL DEFAULT '{}',
            created_at TEXT NOT NULL, finished_at TEXT
        );
        CREATE INDEX IF NOT EXISTS runs_workspace ON runs(workspace_id,created_at);
        CREATE TABLE IF NOT EXISTS memos(
            id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            dataset_id TEXT NOT NULL REFERENCES datasets(id), scenario_hash TEXT NOT NULL,
            content TEXT NOT NULL, status TEXT NOT NULL, approved_by TEXT,
            created_at TEXT NOT NULL, approved_at TEXT
        );
        CREATE TABLE IF NOT EXISTS audit(
            id __AUDIT_ID__ __AUDIT_KEY__,
            workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            action TEXT NOT NULL, details TEXT NOT NULL, created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS rate_limits(
            bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, reset_at DOUBLE PRECISION NOT NULL
        );
        """.replace("__AUDIT_ID__", audit_id).replace("__AUDIT_KEY__", audit_key)
        if postgres:
            for statement in schema.split(";"):
                if statement.strip():
                    c.execute(statement)
        else:
            c.executescript(schema)
        # In-flight jobs are recoverable instead of being silently abandoned on a restart.
        c.execute(
            "UPDATE runs SET status='interrupted',stage='Resume available' WHERE status IN ('running','queued')"
        )


def audit(c, workspace: str, action: str, details: dict):
    c.execute(
        "INSERT INTO audit(workspace_id,action,details,created_at) VALUES(?,?,?,?)",
        (workspace, action, encode(details), now()),
    )


def stale_memos(c, workspace: str):
    c.execute("UPDATE memos SET status='stale' WHERE workspace_id=? AND status!='stale'", (workspace,))
